# Generated by Django 5.0.3 on 2024-03-27 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('method', models.TextField()),
                ('prep_time', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(upload_to='recipes/')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookapp.cuisine')),
            ],
        ),
    ]
