# Generated by Django 5.0.3 on 2024-04-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=2)),
                ('weight', models.IntegerField(max_length=5)),
                ('height', models.IntegerField(max_length=3)),
                ('country', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('allergies', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
