# Generated by Django 5.0.3 on 2024-04-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0002_cures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cures',
        ),
    ]
